### PR TITLE
Add treatment of single quotes for racket

### PR DESCRIPTION
**Pull request by pmatos**
Nothing should be done for single quotes in racket.

### CODE REVIEW

**Comment by Fuco1** [comment]
This is already configured in `smartparens-config.el`, is there any reason you are not using that?

**Comment by pmatos** [comment]
is that something I need to explicitly require? Currently I only require smartparens-racket which does not have that set.

**Comment by Fuco1** [comment]
@pmatos Fair enough.  The `-config` file is an "entry point" to the preconfigured setup and it contains the setup for all the lisp languages.  I don't think there's much harm in having this duplicated though for people who only wish to use one language.

**Comment by pmatos** [comment]
OK, Was not aware of that. Thanks for merging.

**Pull request merged**
