### PR TITLE
Add GitHub issues template

### PR DESCRIPTION
**Pull request by xiongtx**
An issue template should cut down on the number of incomplete bug reports.

### CODE REVIEW

**Comment by xiongtx** [comment]
Ping @Fuco1 🙂

**Comment by Fuco1** [comment]
@xiongtx oh dear, I'm terribly sorry! I started the review with the comment above but never "submitted" it :D Apparently github requires you to press the "send" button twice.  That was 18 days ago so I assumed this one was on you :D

Please give your opinion on the review and then we can move forward!

**Comment by xiongtx** [comment]
I added "Active major mode" to the template.

I'd disagree that this template is useful only for bug reports. The "expected behavior--actual behavior" format is equally useful for feature requests. 

You wouldn't submit a stacktrace for a feature request, of course, but things like `smartparens` version remain important. It is not uncommon for users to request a feature that already exists in the latest build, and for the confusion to clear up only after revealing that they're using an older version of the package.

**Comment by Fuco1** [comment]
That's true, thanks for that point.  Good to merge on my side :)

**Pull request merged**
