### PR TITLE
JavaScript support

### PR DESCRIPTION
**Pull request by marinintim**
Hello! I want to support JavaScript in smartparens.

This pull request adds smartparens-javascript, which I plan to expand later. Right now, it fixes issue with creating spaces around dots.

### CODE REVIEW

**Comment by Fuco1** [comment]
Hi, thanks for taking the time to do this!

Could I bother you to add a test case which "confirms" the change?  So that we are sure not to break this later on.  You can look in `test/smartparens-<LANGUAGE>-test.el` files to get some inspiration.  The python and rust ones are pretty clean.

**Comment by marinintim** [comment]
@Fuco1: hi, I've added a test file, do I need to add it somewhere else?

**Comment by Fuco1** [comment]
You placed it correctly, you can see it being executed on Travis.  But the code doesn't seem to work for some reason :O (the test fails correctly because the result is incorrect).

Is javascript-mode built-in? If not, you would need to add it to `Cask` as well to get it installed during the test setup.

**Comment by marinintim** [comment]
Fuco1: could you check smartparens-javascript.el? It looks like my code is not applied for this temporary buffer in tests. If I execute code manually from smartparens-javascript.el, I see it working in *scratch* buffer with javascript-mode. Also, javascript-mode is a built-in mode.

I'm new to Elisp, so I could easily mess something up.

**Comment by Fuco1** [comment]
It seems `javascript-mode` is aliased to `js-mode`... in some versions of Emacs, and so when I compare the mode symbol returned by `major-mode` they don't match your list.  Try adding `js-mode` to the list of mode where we apply this change.  That should work.

**Comment by marinintim** [comment]
@Fuco1: could you take a look at test results? It seems that at some point it stalled in unrelated place, but I could miss something. I've added `js-mode` to the list of modes.

**Comment by Fuco1** [comment]
I have just experienced the same issue working on a different branch.  I've reported it back to undercover: https://github.com/sviridov/undercover.el/issues/25

I guess we'll have to wait now :/

**Comment by marinintim** [comment]
@Fuco1: Hi, is there any updates on undercover issue?

**Comment by Fuco1** [comment]
No, and I'm starting to have problems in other projects as well.  I think I will disable it for now, this PR is good to go.

**Comment by marinintim** [comment]
@Fuco1: so you would merge it now?

**Comment by Fuco1** [comment]
@marinintim I've rebased and cleaned up the history, it is now on master.

Thanks for the contribution!

**Comment by yqrashawn** [comment]
Hi @marinintim, what's your plan for js with sp. I think there need to be a `javascript-sexp` distinguish by `{...}`, `[ ( or , ]{...}[ ) or , ]` for fast navigation, and normal sexp for string manipulation.

**Pull request closed without merging**
