### PR TITLE
Fix python-indent-dedent-line-backspace in strict mode

### LINKED ISSUE #552: Incorrect paren deleted in python-mode with smartparens-strict-mode
```python
return foo(bar, lambda x: baz(x))|
```

Pressing backspace will remove the end paren, leaving the parens unbalanced.

### PR DESCRIPTION
**Pull request by PythonNut**
This should fix #552.

### CODE REVIEW

**Comment by Wilfred** [comment]
Works beautifully! :) Would you mind adding a test?

**Comment by Fuco1** [comment]
You don't test whether the strict mode is enabled.

**Comment by PythonNut** [comment]
@Fuco1 ah, I thought that `sp-backward-delete-char` did the testing.

**Comment by Fuco1** [comment]
Me too, but it seems it doesn't.  Maybe we should add it there as a separate patch?

**Comment by Fuco1** [comment]
Hi.  I would prefer you add the test to the advice, because I can imagine sometimes you might want to call the method outside of the strict mode (from code).  Plus it only activates in strictmode anyway (via the keymap) so having the test there would be a duplication.

In case of misunderstanding, I think @Wilfred ment a test -> a unit test, I ment a test for the setting in code (that is an `if` condition or whatever).

If you don't know how to add a regression test that's my fault as I still haven't written the documentation :/

**Comment by PythonNut** [comment]
> In case of misunderstanding, I think @Wilfred ment a test -> a unit test, I ment a test for the setting in code (that is an if condition or whatever).

Ah. I see.

> If you don't know how to add a regression test that's my fault as I still haven't written the documentation :/

Yeah, I'll look into it. I'm not that familiar with testing in Elisp, but I think I looked at the code the other day and it wasn't too bad.

**Comment by PythonNut** [comment]
@Wilfred I've added a unit test.

@Fuco1 I've added a runtime check for `smartparens-strict-mode`.

**Comment by Fuco1** [comment]
Great, thanks!

**Comment by Wilfred** [comment]
Thanks @PythonNut :)

**Pull request merged**
