### PR TITLE
[Fix #765] Fix hungry-delete-forward

### LINKED ISSUE #765: smartparens-strict-mode and hungry-delete-mode break sp-delete-char
## Expected behavior

enable `hungry-delete-mode`, press `C-d` which is bound to `sp-delete-char` should delete work just like `delete-char` when not attempting to delete any non-whitespace character.

## Actual behavior

Pressing `C-d` which is bound to `sp-delete-char` gives me this error:

```
sp-delete-char: Wrong number of arguments: #[(n &optional killflag) "¨ÄÅÆD\"Ç .	.ÈU.	É=(ÊË Ì \"Ë Ì |
7Í\"Î " [n delete-active-region current-prefix-arg killflag signal wrong-type-argument integerp use-region-p 1 kill ...] 4 ("/Users/csraghunandan/.emacs.d/elpa/hungry-delete-20170411.1802/hungry-delete.elc" . 1966) "p
P"], 0
```

## Steps to reproduce the problem
enable `hungry-delete-mode` and `smartparens-strict-mode` and press `C-d` to delete a non-whitespace character

## Backtraces if necessary (`M-x toggle-debug-on-error`)

```
Debugger entered--Lisp error: (wrong-number-of-arguments #[(n &optional killflag) "\250\204\304\305\306D\"\210\307 \203.	\203.\310U\203.	\311=\203(\312\313 \314 \"\207\313 \314 |\207
\2037\315\"\207\316 \207" [n delete-active-region current-prefix-arg killflag signal wrong-type-argument integerp use-region-p 1 kill kill-region region-beginning region-end delete-char hungry-delete-forward-impl] 4 ("/Users/csraghunandan/.emacs.d/elpa/hungry-delete-20170411.1802/hungry-delete.elc" . 1966) "p
P"] 0)
  hungry-delete-forward()
  sp-delete-char(nil)
  funcall-interactively(sp-delete-char nil)
  call-interactively(sp-delete-char nil nil)
  command-execute(sp-delete-char)
```

## Environment & version information

- `smartparens` version:  20170629.1338
- Emacs version (`M-x emacs-version`): 26.0.50 built from emacs master build
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla 
- OS: Mac OS Sierra

ps: one of the latest commits caused breakage. I used to use the answer provided for workaround for `hungry-delete-mode` and `smartparens-strict-mode` in [here](https://emacs.stackexchange.com/questions/29476/always-remove-brackets-by-pairs-fix-hungry-delete-mode-and-smartparens-strict)

### PR DESCRIPTION
**Pull request by therockmandolinist**

### CODE REVIEW

**Comment by Fuco1** [comment]
We should probably add some tests so that this won't bite us in the butt in the future.  Can you do that or should I cook some up?

**Comment by therockmandolinist** [comment]
@Fuco1 while that seems reasonable, I know next to nothing about writing tests - might be better if you do.

**Comment by Fuco1** [comment]
@therockmandolinist can you enable pushing to your branch? There should be a button somewhere in the right column "Enable maintainer edits" or something like that.  It will allow me adding commits to your branch so that we can then merge it all together.

See github docs https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by Fuco1** [comment]
Either way thanks for providing the fix so quick!  I was just about to do it myself after finishing the other PR but you were faster :)

**Comment by therockmandolinist** [comment]
@Fuco1 "Allow edits from maintainers" is already checked?

**Comment by Fuco1** [comment]
@therockmandolinist oh okey.  The thing is that I don't see it :D Github sometimes is silly.

I'll add the tests right away then.

**Comment by Fuco1** [comment]
Thanks again!

**Pull request merged**
