### PR TITLE
Clarify testing.

### LINKED ISSUE #515: Clarify how to write tests
It's not immediately clear how to contribute features to smartparens with tests. I understand that the ecukes tests are no longer used.

### PR DESCRIPTION
**Pull request by Wilfred**
Document how to run tests, and remove the remaining bits of ecukes.

Closes #515.

### CODE REVIEW

**Comment by Fuco1** [comment]
I wanted to go over the ecukes tests and rewrite them in ert so we don't lose data.  I think most of the features are duplicated but not everything.

**Comment by Wilfred** [comment]
OK, how about I just document the current smartparens approach to tests? PR updated.

**Comment by Fuco1** [comment]
You can also run a subset of tests by

    cask exec ert-runner --reporter ert -p sp-splice-sexp-killing-around

where whatever is after `-p` is taken as a pattern (I think regexp).

Also please add a note that the ert tests follow conventions of https://github.com/rejeep/ert-runner.el .

I think I'll give you push access to this repo so we can both work on the branches and then merge them in, what do you think?

**Comment by Wilfred** [comment]
I'm happy with that. There have been a few minor smartparens I've been meaning to work on recently, as I use smartparens quite a bit. Whatever makes your life easiest really.

**Comment by Fuco1** [comment]
I've added you already.

What with this, will you add the notes or do you want to move the branch here? (I'm not sure if that's possible on github, and I don't know enough git to do that ;D)

**Comment by Wilfred** [comment]
OK, I've added a note regarding ert-runner and merged this.

**Comment by Fuco1** [comment]
I don't see the note.  Are you sure you pushed it to this repo and not your clone?

**Comment by Wilfred** [comment]
Yep, https://github.com/Fuco1/smartparens/commit/208ca8c6de22f8b2e449b8efdeb45c287bde8861 contains a link to ert-runner.

**Pull request merged**
