### PR TITLE
Use while-no-input from Emacs 27

### PR DESCRIPTION
**Pull request by aaronjensen**
This should speed up responsiveness without the Quit bug. See #943 and #946.

### CODE REVIEW

**Comment by aaronjensen** [comment]
No, it includes the bug fix for ‘while-no-input’ from emacs 27 which should fix the quit error.

**Comment by aaronjensen** [comment]
@duianto could you give this patch a shot on Emacs 26 please?

**Comment by duianto** [comment]
It seems to be working as expected.

There are no quit messages or selection cancellations, and there's no delay when the cursor is moved over the opening parenthesis of the function:
```elisp
(defun create-spacemacs-theme (variant theme-name)
```
in:
https://github.com/nashamri/spacemacs-theme/blob/4dde3005613f484d250ea796185b0dddbc094a86/spacemacs-common.el#L107

The local Spacemacs location is in:
c:/Users/username/.emacs.d/core/libs/spacemacs-theme/spacemacs-common.el:107 

The delay does occur with the current version of Smartparens (without this patch).

This delay seems to have been the original reason for adding the previous (now reverted): `while-no-input`
Use while-no-input in show-pair-function. #943

#### System Info :computer:

The patch was applied to: smartparens-20190112.1318

- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 990290e24)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp git helm html ibuffer markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
This might be the thread where the function was introduced, at least it's discussed there.
https://lists.gnu.org/archive/html/bug-gnu-emacs/2018-06/msg00340.html

**Comment by aaronjensen** [comment]
@Fuco1 This branch has been rebased and should be ready to merge. Emacs 27 is released now and I've confirmed that this is the released version of `while-no-input`

**Comment by ThibautVerron** [comment]
Aha, I was missing this bit of history. I will port it in my local copy and give it a test.

Maybe to be more future-proof, we would want to just have the macro expand `while-no-input` if `emacs-version` is at least 27?

**Comment by aaronjensen** [comment]
@ThibautVerron sure, updated.

**Comment by ThibautVerron** [comment]
Cool. :)

It's really nitpicking, but is there a good reason for putting the test inside the macro, as opposed to having two different defmacro's depending on the version?

**Comment by aaronjensen** [comment]
@ThibautVerron good idea, I hadn't thought of that. I simply aliased it instead of declaring a macro for Emacs 27+

**Comment by Fuco1** [comment]
I'm going to pull this locally and use it for a day, if it works fine on my prehistoric E26.1 I think it's safe to go ahead.

**Comment by Fuco1** [comment]
Haven't yound any problems so I'm merging this.  Thanks for the work everybody, good job!

**Pull request merged**
