### PR TITLE
 Bugfixes and improvements to `sp-kill-sexp`

### PR DESCRIPTION
**Pull request by Wilfred**
This pull request includes:

* Tests for `sp-kill-sexp` based on the examples in the docstring
* A fix for a bug I found when testing those examples (SP is confused about negative prefix arguments)
* A fix for #572 (handling punctuation) by starting the kill from the current point position

I've not explored this part of the code before, so please let me know if I've done anything silly :)

### CODE REVIEW

**Comment by Fuco1** [comment]
I test commands using the `sp-test-command` macro, it's in the `smartparents-commands-test.el` file.  It has the added bonus of automatically checking if point ends up where we want, and you can perform sequences of multiple steps along the way.

**Comment by Fuco1** [comment]
And which example did not work properly?  I'm not sure testing for 4 or negative makes sense in the way I intented the command to work.

**Comment by Wilfred** [comment]
4675763b0fffe4e46c9cfbe97b907c419ec910cc shows the example that doesn't work. The relevant lline from the docstring of `sp-kill-sexp`:

```
 (1 2 3 4| 5 6)    -> (|5 6)      ;; - \\[universal-argument]
```

**Comment by Fuco1** [comment]
Works for me, you need to do: `C-- C-u sp-kill-sexp`

**Comment by Wilfred** [comment]
Yikes, I had no idea you could pass negative prefix arguments like that. I was doing `C-u - M-x sp-kill-sexp`. Should that do the same thing? That was what I was expecting.

**Comment by Fuco1** [comment]
Nope, not the same thing.  `C-u` initiates the "prefix argument map" in which numbers specify the number (so you just do `C-u 2` instead of `C-u C-2`... or just `C-2`) and - specifies negation *in that mode*.  If you do `C--` before, it stores the negative and then `C-u` sends in `(4)` which gets negated---or if you follow up with numbers it will pass onto the numbers.

It's a bit crazy :P

**Comment by Wilfred** [comment]
OK, that kind of makes sense :). I'll update the PR.

**Comment by Wilfred** [comment]
Updated, let me know what you think.

**Comment by Fuco1** [comment]
Seems to work so I'm OK with merging this.

You rewriting test from the docstrings gave me the idea that maybe we could auto-generate tests from the documentation (kind of like dash)... but I'm not sure if it's worth the trouble. (haskell also has something similar)

**Pull request merged**
