### PR TITLE
smartparens-python.el: auto-insert a colon in function definitions

### PR DESCRIPTION
**Pull request by Hi-Angel**
I'm slowly upstreaming various helpers from my Emacs config. This one I've used for a few years I think. Never was getting any misses *(the context for function definition in python is pretty unambiguous)*, so barring something I might have missed while preparing the code for upstreaming, this should be safe.

### CODE REVIEW

**Comment by Hi-Angel** [comment]
Even, wait a second, I figured I can improve it by moving the `(forward-char)` to after successful detection

**Comment by Hi-Angel** [comment]
Done, it should be better now.

**Comment by Hi-Angel** [comment]
**upd**: eliminated an excess `when`

**Comment by Fuco1** [comment]
This is very fortunate as I just started writing more python :D :+1: 

I think it would be nice with a configuration option.  We can enable it by default so people can discover it, but then those who don't like it can disable it with a setting.

We can start a group `smartparens-python` if it doesn't exist yet.

**Comment by Hi-Angel** [comment]
> This is very fortunate as I just started writing more python :D 

^_____^

> I think it would be nice with a configuration option. We can enable it by default so people can discover it, but then those who don't like it can disable it with a setting.
> 
> We can start a group `smartparens-python` if it doesn't exist yet.

There is `smartparens-python`. Is it enough, or do you want me to surround the colon auto-completion specifically with an opt-out option?

**Comment by Fuco1** [comment]
Yea, I ment a `defgroup`, similar to 

```
(defgroup smartparens ()
  "Smartparens minor mode."
  :group 'editing
  :prefix "sp-")
```

so that the options for python are grouped under that (setting `smartparens` group as parent).  The opt-out option would then be placed there.

**Comment by Hi-Angel** [comment]
Done now, please see if it looks okay. I didn't work with groups before, but hopefully I did everything correctly.

**Review by Fuco1 — CHANGES_REQUESTED** [review]
all the functions and variables need to have the `sp-python` prefix.

the group stuff seems fine to me

**Comment by Hi-Angel** [comment]
> all the functions and variables need to have the `sp-python` prefix.

Oh, yeah, right, done. I kinda thought a group limits a visibility scope, but I admit that was silly of me, in Lisp everything is global besides `let` expression.

**Review by Fuco1 — APPROVED** [review]

**Comment by Fuco1** [comment]
> I kinda thought a group limits a visibility scope, but I admit that was silly of me

I also thought so, especially since you can also specify the `:prefix` parameter to the group which kind of suggests it's going to auto-prefix or something.  But it's only related to some UI things in customize.

LGTM, thanks for the patch!

**Pull request merged**
