### PR TITLE
Fix #1077

### LINKED ISSUE #1077: Error when loading smartparens
Getting this error when loading smartparens after pulling the latest code: `Eager macro-expansion failure: (wrong-type-argument listp [(first-item . rest-items) (sp-get-list-items)])`.

### PR DESCRIPTION
**Pull request by sirikid**

### CODE REVIEW

**Comment by duianto** [comment]
Confirmed.

`M-x smartparens-mode` shows the message:
>Eager macro-expansion failure: (wrong-type-argument listp [(first-item . rest-items) (sp-get-list-items)])

This PR fixes it.

### System Info
```
smartparens-20210213.1851
GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-08-21
Windows 10 2004
```

**Comment by veronikazaglotova** [comment]
Oh god it's been 7 days already why don't they merge this

**Comment by sunlin7** [comment]
Affect by this issue, and applying this patch in my local can resolve the issue. 
Look forward it's available in official.

**Comment by conao3** [comment]
@Fuco1, ping? That first report was 3weeks ago.

**Comment by Fuco1** [comment]
Thank you all for patience, I had some personal problems in the last two months-ish that didn't allow me to tend to my projects.

Hopefully I'll manage to clean the backlog in April.

**Comment by sirikid** [comment]
Sorry for the inconvenience caused by my previous PR

**Pull request merged**
