### PR TITLE
Handle ' in rust-mode intelligently.

### LINKED ISSUE #512: Don't treat ' as a delimiter in rust-mode
In rust, lifetime specifiers look like this: `'foo`. Whilst it's also possible to use `'` for single characters, e.g. `'h'`, lifetime specifiers are more common.

### PR DESCRIPTION
**Pull request by Wilfred**
Fixes #512.

### CODE REVIEW

**Comment by Fuco1** [comment]
You can use `sp-test-with-temp-buffer` instead of your own setup function.  It should be understandable from the docstring or you can search the tests for an example.

I will write something about the "test framework" hopefully soon enough :P

**Comment by Wilfred** [comment]
Aha, I didn't know about `sp-test-with-temp-buffer`. I've pushed a new commit, let me know if you'd prefer I squashed it.

**Comment by Fuco1** [comment]
Yes please, squash and then we merge! Thanks.

**Comment by Wilfred** [comment]
Squashed :)

**Comment by Fuco1** [comment]
Bam, thanks!

**Comment by skeuomorf** [comment]
Nice! Thanks @Wilfred and @Fuco1 :)

**Pull request merged**
