### PR TITLE
Interactive behaviour for sp-{next,previous}-sexp

### LINKED ISSUE #541: sp-next-sexp alternative fallback
"If there is no next expression at current level, jump one level up (effectively doing `sp-backward-up-sexp`)."

I'm not too keen on this fallback behaviour, what do you think about changing it to:

"If there is no next expression at the current level, jump one level up and retry." (which would have the effect of going to the next s-exp at whatever level has one)

### PR DESCRIPTION
**Pull request by fommil**
closes #541

### CODE REVIEW

**Comment by fommil** [comment]
green lights, so its got to be awesome!

I would add a test but I couldn't find one for next/previous

**Comment by Wilfred** [comment]
@fommil I've pushed a few example tests, is that useful for you?

Looking at the code, could you please give the defcustom a more explicit name? DWIM can mean very different things to different people. Perhaps `sp-move-up-at-end`?

One other question: how is this different from `sp-forward-sexp`? I'm probably being stupid, but as far as I can see, `sp-forward-sexp` has this behaviour already.

**Comment by fommil** [comment]
`sp-forward-sexp` places the point at the end of the sexp, doesn't it?

I'll add some tests and have a think about the defcustom name.

**Comment by Wilfred** [comment]
Ah, I think Fuco's example mislead me.

```lisp
;; sp-next-sexp
(foo|) (bar) -> |(foo) (bar)

;; sp-forward-sexp
(foo|) (bar) -> (foo)| (bar)
```

Perhaps a more interesting case is:

```lisp
;; sp-forward-sexp
((foo|)) (bar) -> ((foo)|) (bar)

;; whereas you want to move straight to the next sexp:
((foo|)) (bar) -> ((foo)) |(bar)
```

I suppose you could write a `defcustom` like this?

```lisp
(defcustom sp-movement-at-end 'backward-up
  "Controls the behaviour when the user tries to move beyond
the last sexp at the current level with `sp-next-sexp'."
  :type '(radio
          (const :tag "Move backwards, up one level" 'backward-up)
          (const :tag "Move forwards to the next sexp, up many level if necessary" 'next-sexp)))
```

It might be nice if this took a movement function rather than symbols, but I don't think smartparens currently has a function for this exact behaviour you're looking for.

**Comment by fommil** [comment]
umm, that's not what I'm trying to do. Have a look at my examples in the updated docs to show what I mean. I don't really care about the end/beginning behaviour.

**Comment by fommil** [comment]
ok, almost done with tests. Are you ok with me making the defcustom on by default?

**Comment by fommil** [comment]
ok, tests added. Any better ideas on the name? I can't think of anything.

**Comment by Fuco1** [comment]
Wow, lots of work done here :) I'm really sorry but I'm totally wasted today, I will review this asap, but not now.  Thanks for taking it up Sam!

**Comment by fommil** [comment]
aaah :christmas_tree: that time of year when its a race between passing out with all the drink, or tidying up all those `.emacs` niggles you've putting off for ages.

**Comment by Fuco1** [comment]
The more I think about this I think the new behaviour should simply be the default.  We should also mark the function as "do not use from code" (as it's not a primitive like `sp-forward-sexp`).

I only used it once in `smartparens-html.el` and that can probably be easily fixed.

What about the case `((foo|)) (bar)` ? I think a useful invariant to introduce would be "point should never end back from where it started".  That way we will simply retry the procedure until point goes forward or there is nowhere to move (we're at the last form).

What do you think?

**Comment by fommil** [comment]
Yup, that'd be nice! Now that Xmas is over I won't have so much time to do that though, sorry

**Comment by Fuco1** [comment]
Most of the stuff you wrote seems to be reusable for this purpose, just throwing a couple loops around somewhere.

I'll try to merge it into a branch and work on that, then we merge from there.  If you want to add more changes it would be simpler to work in this repo directly, I'm OK with giving you push access.

**Comment by fommil** [comment]
Cool. Can you please merge to master as is, just so I can use this?

**Comment by fommil** [comment]
@Fuco1 any plans to merge?

**Comment by fommil** [comment]
@fuco1 ping

**Comment by Fuco1** [comment]
Right, I'll rewiew this over the weekend, thanks for the ping :P

**Comment by fommil** [comment]
I only noticed because github added a new feature to show all your PRs in flight :smile:

**Comment by fommil** [comment]
Heh spotted again thanks to more github upgrades. I'm surviving without this but it would be good.

**Comment by Fuco1** [comment]
Looking at the test cases, it seems to me that this can be achieved by ignoring symbols:

    (setq-local sp-navigate-consider-symbols nil)

Try this in scratch buffer.  If not, can you add some case where it doesn't only "ignore" symbols?

**Comment by fommil** [comment]
Might be a while, I'm on holiday and no access to a computer.

**Comment by fommil** [comment]
I appear to have completely forgotten about this PR. I can't even remember creating it.

**Comment by Fuco1** [comment]
Damn I suck.  This has been opened for two years now :/

I'm going to solve this right now :)

**Comment by fommil** [comment]
awesome, although I thought I was the one holding it up so don't feel so bad :smile:

**Comment by Fuco1** [comment]
Implemented in 40eccef.

The behaviour is such that with the option turned on the `sp-next-sexp` will keep going until the point ends up 

1) at the beginning of some sexp
2) being at a greater position than where it started from

The only exception is at the end of the buffer at the end of the sexp where there is no sexp forward, it will jump to the beginning of the last sexp in the buffer.

Analogically for the previous variant.

I renamed the option to `sp-navigate-interactive-always-progress-point` it is on by default and in the 2.0 release it will become non-configurable because it is simply the most logical behaviour.

THanks everyone for input!

**Comment by fommil** [comment]
Awesome! Thank you so much :-)

**Pull request closed without merging**
