### PR TITLE
Don't reindent Python code after kills

### LINKED ISSUE #529: Don't change indentation when deleting words/symbols
Consider the code:

```python
def foo():
    if bar:
        baz()
    quuz = biz.boz|
```

`sp-backward-kill-word` and `sp-backward-kill-symbol` in `python-mode` both produce:

```python
def foo():
    if bar:
        baz()
        quuz = biz.|
```

This doesn't seem to occur for other whitespace sensitive languages (e.g. coffeescript).

### PR DESCRIPTION
**Pull request by Wilfred**
Fixes #529.

### CODE REVIEW

**Comment by Fuco1** [comment]
Squash please :)

**Comment by Wilfred** [comment]
Done :)

**Comment by Fuco1** [comment]
Thanks for consolidating the other test too.

**Comment by Fuco1** [comment]
Oh shit... closing this makes it unmeargable.

**Pull request merged**
