### PR TITLE
When slurping forward, don't include punctuation at end of line.

### LINKED ISSUE #534: sp-slurp-hybrid-sexp should not surround punctuation
Given the JS:

```js
var foo = |baz;
```

I want to wrap `baz` in a call to `bar`. I type `bar(` and get:

```js
var foo = bar(|)baz;
```

I now call `sp-slurp-hybrid-sexp`:

```js
var foo = bar(|baz;)
```

whereas I wanted:

```js
var foo = bar(|baz);
```

A similar issues occurs in Python with `for i in len()foo.bar:` to `for i in len(foo.bar:)`.

### PR DESCRIPTION
**Pull request by Wilfred**
Fixes #534.

Let me know what you think of this approach. I've added tests, so I think the code is sane, but it's quite possible I've missed corner cases.

### CODE REVIEW

**Comment by Fuco1** [comment]
Sometimes you want to move the punctuation.  In C++ classes end with `};`, in many lanugages with lambdas you can have inline `;` or `,` which should move along (java, php, c#?).

I think this should be determined partially by syntax tables and partially by the user setting, similar to prefix.

**Comment by Fuco1** [comment]
For a concrete example, consider

```c++
class foo {
public:
    int a;
};

int b = 7;
```

**Comment by Fuco1** [comment]
It seems I don't understand the problem :D Because the example above works fine with your patch or without.

**Comment by Wilfred** [comment]
Previously, we always included the punctuation at the end of the line. This patch introduces a new heuristic:

* If your open and close parens will be on the same line, don't include the punctuation. `foo(|)bar;` -> `foo(bar);`
* If your parens will be on different lines, do include the punctuation. `while () {|}\nfoo();` -> `while () {\n   foo();\n}`

This works really well in my testing. The only corner case I can think of is `bar(|)1.` -> `bar(1).`. I think this is a net improvement though.

@Fuco1 are you happy with this?

**Comment by Fuco1** [comment]
I see.  Yes that sounds reasonable.

Could you please add the test case for C++ above? That tests that the punctuation *after* the closing delimiter moves along with it if necessary.  Then we can merge :)

**Comment by Wilfred** [comment]
Test added :)

**Comment by Fuco1** [comment]
Awesome, thanks a lot for your work! This tends to get annoying at times so I really appreciate someone digging into the crap :D

**Pull request merged**
